version: '3'
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: machi
            POSTGRES_PASSWORD: machi
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        restart: always
        user: root
